# Generated by Django 3.0.3 on 2020-03-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200304_1747'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City1',
            new_name='City',
        ),
    ]
